# Use an official MySQL runtime as a parent image
FROM mysql:latest

# Set the MySQL root password
ENV MYSQL_ROOT_PASSWORD=root

# Create a database and user
ENV MYSQL_DATABASE=myclinic
ENV MYSQL_USER=root
ENV MYSQL_PASSWORD=root

# When container starts, execute the following SQL script
COPY ./myclinic.sql /docker-entrypoint-initdb.d/
